[2024-02-17 17:39:58,250: INFO: main: Welcome to cnnClassifier!]
[2024-02-18 20:31:44,771: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-18 20:31:44,771: ERROR: main: [Errno 2] No such file or directory: 'config\\config.yaml']
Traceback (most recent call last):
  File "D:\Projects\CNN-Chest-Cancer-Classification\templates\main.py", line 9, in <module>
    obj.main()
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\pipeline\Stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\config\configuration.py", line 12, in __init__
    self.config = read_yaml(config_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehai\anaconda3\envs\ctscan\Lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\utils\common.py", line 36, in read_yaml
    raise e
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\utils\common.py", line 29, in read_yaml
    with open(path_to_yaml) as yaml_file:
         ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config\\config.yaml'
[2024-02-18 20:32:16,785: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-18 20:32:16,785: ERROR: main: [Errno 2] No such file or directory: 'config\\config.yaml']
Traceback (most recent call last):
  File "D:\Projects\CNN-Chest-Cancer-Classification\templates\main.py", line 9, in <module>
    obj.main()
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\pipeline\Stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\config\configuration.py", line 12, in __init__
    self.config = read_yaml(config_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehai\anaconda3\envs\ctscan\Lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\utils\common.py", line 36, in read_yaml
    raise e
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\utils\common.py", line 29, in read_yaml
    with open(path_to_yaml) as yaml_file:
         ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config\\config.yaml'
[2024-02-18 20:33:31,645: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-18 20:33:31,645: ERROR: main: [Errno 2] No such file or directory: 'config\\config.yaml']
Traceback (most recent call last):
  File "D:\Projects\CNN-Chest-Cancer-Classification\templates\main.py", line 9, in <module>
    obj.main()
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\pipeline\Stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\config\configuration.py", line 12, in __init__
    self.config = read_yaml(config_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehai\anaconda3\envs\ctscan\Lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\utils\common.py", line 36, in read_yaml
    raise e
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\utils\common.py", line 29, in read_yaml
    with open(path_to_yaml) as yaml_file:
         ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config\\config.yaml'
[2024-02-18 20:34:56,147: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-18 20:34:56,148: ERROR: main: [Errno 2] No such file or directory: 'config\\config.yaml']
Traceback (most recent call last):
  File "D:\Projects\CNN-Chest-Cancer-Classification\templates\main.py", line 9, in <module>
    obj.main()
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\pipeline\Stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\config\configuration.py", line 12, in __init__
    self.config = read_yaml(config_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehai\anaconda3\envs\ctscan\Lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\utils\common.py", line 36, in read_yaml
    raise e
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\utils\common.py", line 29, in read_yaml
    with open(path_to_yaml) as yaml_file:
         ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config\\config.yaml'
[2024-02-21 22:42:52,292: INFO: <ipython-input-1-5d38d4931bf5>: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-21 22:42:52,293: ERROR: <ipython-input-1-5d38d4931bf5>: [Errno 2] No such file or directory: 'config\\config.yaml']
Traceback (most recent call last):
  File "<ipython-input-1-5d38d4931bf5>", line 12, in <module>
    obj.main()
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\config\configuration.py", line 13, in __init__
    self.config = read_yaml(config_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\mehai\anaconda3\envs\ctscan\Lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\utils\common.py", line 36, in read_yaml
    raise e
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\utils\common.py", line 29, in read_yaml
    with open(path_to_yaml) as yaml_file:
         ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config\\config.yaml'
[2024-02-22 20:27:18,565: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-22 20:27:18,567: ERROR: main: [Errno 2] No such file or directory: 'config\\config.yaml']
Traceback (most recent call last):
  File "D:\Projects\CNN-Chest-Cancer-Classification\templates\main.py", line 13, in <module>
    obj.main()
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\config\configuration.py", line 13, in __init__
    self.config = read_yaml(config_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehai\anaconda3\envs\ctscan\Lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\utils\common.py", line 36, in read_yaml
    raise e
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\utils\common.py", line 29, in read_yaml
    with open(path_to_yaml) as yaml_file:
         ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config\\config.yaml'
[2024-02-22 20:30:42,882: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-22 20:30:42,882: ERROR: main: [Errno 2] No such file or directory: 'config\\config.yaml']
Traceback (most recent call last):
  File "D:\Projects\CNN-Chest-Cancer-Classification\templates\main.py", line 13, in <module>
    obj.main()
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\config\configuration.py", line 13, in __init__
    self.config = read_yaml(config_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehai\anaconda3\envs\ctscan\Lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\utils\common.py", line 36, in read_yaml
    raise e
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\utils\common.py", line 29, in read_yaml
    with open(path_to_yaml) as yaml_file:
         ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config\\config.yaml'
[2024-02-22 21:17:36,097: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-22 21:17:36,097: ERROR: main: [Errno 2] No such file or directory: 'config\\config.yaml']
Traceback (most recent call last):
  File "D:\Projects\CNN-Chest-Cancer-Classification\templates\main.py", line 13, in <module>
    obj.main()
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\config\configuration.py", line 13, in __init__
    self.config = read_yaml(config_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehai\anaconda3\envs\ctscan\Lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\utils\common.py", line 36, in read_yaml
    raise e
  File "d:\projects\cnn-chest-cancer-classification\src\cnnClassifier\utils\common.py", line 29, in read_yaml
    with open(path_to_yaml) as yaml_file:
         ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config\\config.yaml'
